# Cantidad de interacciones mínimas para usar el algoritmo
MINIMUM_NUMBER_OF_INTERACTIONS = 5

# Cantidad de atracciones que se quieren recomendar
N_RECOMMENDATIONS = 30

# Valor para rellenar a los nulos en el algortimo de recomendación
FILLNA_VALUE = 0

ATTRACTION_TYPES = [
    "airport",
    "american_restaurant",
    "amusement_center",
    "amusement_park",
    "aquarium",
    "art_gallery",
    "athletic_field",
    "bakery",
    "bar",
    "barbecue_restaurant",
    "bed_and_breakfast",
    "bowling_alley",
    "brazilian_restaurant",
    "breakfast_restaurant",
    "brunch_restaurant",
    "cafe",
    "campground",
    "camping_cabin",
    "casino",
    "cemetery",
    "chinese_restaurant",
    "church",
    "city_hall",
    "coffee_shop",
    "cottage",
    "cultural_center",
    "embassy",
    "event_venue",
    "extended_stay_hotel",
    "farmstay",
    "fast_food_restaurant",
    "ferry_terminal",
    "french_restaurant",
    "gift_shop",
    "golf_course",
    "greek_restaurant",
    "hamburger_restaurant",
    "hiking_area",
    "hindu_temple",
    "historical_landmark",
    "hospital",
    "hostel",
    "hotel",
    "ice_cream_shop",
    "indian_restaurant",
    "indonesian_restaurant",
    "italian_restaurant",
    "japanese_restaurant",
    "korean_restaurant",
    "lebanese_restaurant",
    "library",
    "local_government_office",
    "lodging",
    "marina",
    "market",
    "mediterranean_restaurant",
    "mexican_restaurant",
    "middle_eastern_restaurant",
    "mosque",
    "motel",
    "movie_theater",
    "museum",
    "national_park",
    "night_club",
    "park",
    "performing_arts_theater",
    "pizza_restaurant",
    "playground",
    "ramen_restaurant",
    "resort_hotel",
    "restaurant",
    "sandwich_shop",
    "seafood_restaurant",
    "shopping_mall",
    "ski_resort",
    "spa",
    "spanish_restaurant",
    "sports_club",
    "sports_complex",
    "stadium",
    "steak_house",
    "subway_station",
    "supermarket",
    "sushi_restaurant",
    "swimming_pool",
    "synagogue",
    "thai_restaurant",
    "tourist_attraction",
    "train_station",
    "travel_agency",
    "turkish_restaurant",
    "university",
    "vegan_restaurant",
    "vegetarian_restaurant",
    "vietnamese_restaurant",
    "zoo",
]
