services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: attractions
    container_name: attractions
    restart: always
    ports:
      - ${PORT}:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE=${POSTGRES_SERVICE}
      - ATTRACTIONS_API_KEY=${ATTRACTIONS_API_KEY}
