on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      ATTRACTIONS_API_KEY: ${{ secrets.ATTRACTIONS_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_SERVICE: ${{ secrets.POSTGRES_SERVICE }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      USERS_URL: ${{ secrets.USERS_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest-cov

      - name: Run tests
        run: pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          fail_ci_if_error: false
          files: ./coverage.xml,!./cache
          name: codecov-umbrella
